### ISSUE TITLE
Rendering doesn't continue after restart/reload

### ISSUE THREAD

**Issue by leMaik** [leMaik/ChunkyMap#1]

**Comment by rm2023** [comment]
Can confirm this is still a problem in paper-135 with dynmap core=3.1-beta-2-389 and chunkymap 2.4.1. It looks like after a restart, the render "finishes" instantly withthe last message indicating it's spending 0ms/render, which probably indicates something's wrong with the way dynmap/chunkymap is "remembering" the render.
