### ISSUE TITLE
Isometric View Cuts off part of selected chunks

### ISSUE THREAD

**Issue by MattQ012** [leMaik/ChunkyMap#11]
I hope this is the right place to report a bug. When using the Isometric View for a render, part of the selection gets cut off and doesn't render. See this Image for reference: https://imgur.com/a/XysVj46

The Chunks will only get completely loaded if looking 90 Degrees down

**Comment by KasKatto** [comment]
Your using the chunky map software. This repo is for the dynmap plugin. I assume your looking for this [repo instead](https://github.com/llbit/chunky). You should report it there.

**Comment by leMaik** [comment]
@MattQ012 You need to move the camera further up, it's clipping into the ground. As already mentioned, this is the wrong repo, though.
