### ISSUE TITLE
[ChunkyMap 1.x] Wrong tile positions with custom perspective

### ISSUE THREAD

**Issue by mruk** [leMaik/ChunkyMap#24]
INFO: This server is running CraftBukkit version git-Bukkit-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Dynmap version: core=2.6-beta-1-Dev201807081957, plugin=2.6-beta-1-Dev201807082003
ChunkyMap v1.2.0

ChunkyMap renderer seems to have problem with tile addressing when the custom perspective is used.
What I Am think - there is no problem with perspective in single given tile. There is a problem with tile coordinates - they all are seems to be clumped near 0,0.

perspectives.txt

- class: org.dynmap.hdmap.IsoHDPerspective
  name: izo_210
  azimuth: 210
  inclination: 60
  scale: 4

See attached screen - same map, same properties. ChunkyMap tiles are on wrong positions.
On the left -  class: org.dynmap.hdmap.HDMap
On the right - class: de.lemaik.chunkymap.dynmap.ChunkyMap
![bukkit_Dynmap_v26_ChunkyMap-v120](https://user-images.githubusercontent.com/667358/103820683-104bea00-506d-11eb-8fc8-bcb06ed6ae9e.jpg)

**Comment by leMaik** [comment]
Thanks for reporting this! The issue has been fixed in ChunkyMap 2.4.1 (most likely) but I didn't backport the it to ChunkyMap 1.x yet. I'll @ you when it's done :+1:

**Comment by leMaik** [comment]
With Chunky 2.4.0 being releases soon, the next version of ChunkyMap (3.x) will support all Minecraft versions. I'm closing this as won't do because back-porting the fix from 2.x will not happen.
