### ISSUE TITLE
ChunkyMap does not show render info

### ISSUE THREAD

**Issue by Misio12320** [leMaik/ChunkyMap#26]
Hi. The ChunkyMap does not show me in console messages like in Dynmap.
This server is running Paper version git-Paper-439 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[20:08:20 INFO]: Checking version, please wait...
[20:08:21 INFO]: Previous version: git-Paper-434 (MC: 1.16.5)
[20:08:21 INFO]: You are running the latest version
 dynmap version 3.1-beta5-431
ChunkyMap version 2.5.2
Chunky version 1.1.21
Also it does not render, only sends "Can't keep up" into console. help

**Comment by Misio12320** [comment]
Also the TPS is decreasing and server get a lot of lags.

**Comment by leMaik** [comment]
This is not a bug. Rendering with Chunky is slower and uses a lot of CPU so it will take longer to show progress info and if your CPU isn't powerfull enough or you are using too many threads for dynmap/ChunkyMap, your server will lag.

In the future, it will be possible to use [ChunkyCloud](https://chunkycloud.lemaik.de) to render the map externally. More info about that is available on the Chunky Discord.

**Comment by Misio12320** [comment]
@leMaik where is the Discord link?

**Comment by leMaik** [comment]
@Misio12320 Sorry, there you go: https://discord.gg/VqcHpsF
