### ISSUE TITLE
How to add texture pack to dynmap/chunkymap

### ISSUE THREAD

**Issue by disduke** [leMaik/ChunkyMap#31]
Sorry but I have no clue how to add a resource/texture pack ive tried adding the texture pack to the texture pack folder and in worlds.txt adding 
worlds:
  - name: world
    maps:
      - class: de.lemaik.chunkymap.dynmap.ChunkyMap
        name: chunky
        title: World
        perspective: iso_SE_30_hires
        texturepack:name.zip

**Comment by leMaik** [comment]
For future readers:

> Texturepack path, relative to plugins/dynmap. Use this option to specify a texturepack for a map. The texturepack in Dynmap's configuration.txt is ignored by ChunkyMap.
