### ISSUE TITLE
Shadows of very tall structures cut off

### ISSUE THREAD

**Issue by BlackAsLight** [leMaik/ChunkyMap#32]
The shadow from flat map cuts off for very tall structures. 
![Screenshot_2021-04-02 Stagintin Map](https://user-images.githubusercontent.com/44320105/113380331-a753e400-93c7-11eb-8315-4974580bfeb2.png)
![Screenshot_2021-04-02 Stagintin Map(1)](https://user-images.githubusercontent.com/44320105/113380402-dcf8cd00-93c7-11eb-83a1-bd244c0dee7f.png)

**Comment by leMaik** [comment]
There's not much I can do about that. You can increase `chunkPadding` and tune the sun angle by using a template scene.

**Comment by BlackAsLight** [comment]
The `chunkPadding` worked. Thanks.
