### ISSUE TITLE
What if chunky downloads textures and blocks from 1.10 if the server and the map are on 1.12.2?

### ISSUE THREAD

**Issue by SPAWNRYS-ban** [leMaik/ChunkyMap#38]
It just looks very bad due to the lack of some blocks
![Screenshot_2586](https://user-images.githubusercontent.com/68144848/125770484-be069798-6838-4c52-b917-b7b2118d321a.png)
![Screenshot_2585](https://user-images.githubusercontent.com/68144848/125770496-1011f22b-a6ea-480d-bcdc-f8366cc86f6a.png)

**Comment by leMaik** [comment]
That shouldn't happen. You can configure a texture pack and just use the minecraft.jar file of version 1.12 as resourcepack. The readme explains how to configure it

**Comment by leMaik** [comment]
Closing due to lack of information, feel free to re-open if this issue still affects you.
