### ISSUE TITLE
Black Image is being rendered 

### ISSUE THREAD

**Issue by rrionn** [leMaik/ChunkyMap#42]
All of my renders are completely black. Not sure if this is an issue with the file, or I'm just setting it up wrong. I'm using the most recent version of chunkymap with dynmap. 

There's no errors in the logs. Just a black Image.

**Comment by rrionn** [comment]
After speaking with someone, I was told that this current build doesn't work with 1.18. If that's the case my apologies for opening this issue.

**Comment by leMaik** [comment]
Indeed, 1.18 is not supported yet. I'll leave this open until ChunkyMap supports 1.18 (we need Chunky 2.4.x to support 1.18 first and then update ChunkyMap).

**Comment by leMaik** [comment]
New release is coming soon (next weekend), for now you could try building the chunky-2.4 branch by yourself.
