### ISSUE TITLE
Rendering in 1.13.2 renders black

### ISSUE THREAD

**Issue by KasKatto** [leMaik/ChunkyMap#5]
Rendering in 1.13.2 using latest dynmap and chunkymap renders everything black and still takes a lot of CPU time. Possibly due to the new chunk format, which the newest versions of chunky have already updated to.

**Comment by stormboomer** [comment]
I can confirm this is still an issue, even tested it on a fresh server running:
dynmap 3.0-beta-3-160 and ChunkyMap v1.2.0
on a Spigot-5629554-4c8327f (MC: 1.13.2) server

**Comment by leMaik** [comment]
Looks like Chunky would need to be updated. :thinking: I'm not that much into Minecraft anymore lately, but I may look into this.

**Comment by stormboomer** [comment]
would be pretty nice of you if you could update it :) we really want to use the chunky rendering engine for our dynmap

**Comment by leMaik** [comment]
@stormboomer I'd love to see that dynmap! 👍

**Comment by leMaik** [comment]
Rendering MC 1.13 maps will require [Chunky 2](https://chunky.llbit.se/chunky2.html), which has no public library yet.

**Comment by leMaik** [comment]
That was _way_ easier than I thought! :tada: @stormboomer and @KasKatto, please give it a try: https://github.com/leMaik/ChunkyMap/releases/tag/v2.0.0
