### ISSUE TITLE
Wrong Rendering of seaplants

### ISSUE THREAD

**Issue by stormboomer** [leMaik/ChunkyMap#6]
There seems to be a weird interaction with seaplants and Chunky Map

The normal Dynmap renderer renders like this
![image](https://user-images.githubusercontent.com/25079531/62003618-e2dddb80-b119-11e9-8527-2cd68d164737.png)

The Chunky Dynmap renderer renders like this
![image](https://user-images.githubusercontent.com/25079531/62003686-14a37200-b11b-11e9-9f62-6cc5bd7752a9.png)

Ingame looks like this
![image](https://user-images.githubusercontent.com/25079531/62003636-37815680-b11a-11e9-8534-e76b4f9008ad.png)

I'm using a custom Texturepack, but the normal dynmap renderer was able to render successfully, so I gues its not really a texturepack issue.

Server: git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Dynmap: Dynmap v3.0-beta-5-218
ChunkyMap: ChunkyMap-2.0.0 (you might need to update plugin.yml, it still gives 1.2.0 when launched)

**Comment by leMaik** [comment]
It's a chunky issue. Maybe the version that can be downloaded isn't the latest version of Chunky (because https://github.com/llbit/chunky/issues/518 says that it should render fine).

> you might need to update plugin.yml, it still gives 1.2.0 when launched

Yeah, I forgot to bump the version in the plugin.yml yesterday. PR welcome :sweat_smile:

**Comment by leMaik** [comment]
This is a Chunky issue. I get the same behavior when using Chunky 2.0-alpha2. On the homepage, there are far better renders with seagrass, but unfortunately, the code of Chunky 2 doesn't seem to be open source yet. alpha2 looks to be out of date.

**Comment by leMaik** [comment]
Wait… From the Discord, I just saw that Chunky 2.0 beta6 is the latest release. :open_mouth:

**Comment by leMaik** [comment]
@stormboomer Somehow got 2.0-alpha2 as "latest" version when updating Chunky yesterday. I deleted my `.chunky` directory and today I got 2.0-beta6. :man_shrugging: 

I released a new version that includes Chunky 2.0-beta6, please give it a try: https://github.com/leMaik/ChunkyMap/releases/tag/v2.0.1
