### ISSUE TITLE
Add new 1.14 blocks?

### ISSUE THREAD

**Issue by Leonardo-Fiori** [leMaik/ChunkyMap#8]
I don't know if it is on your side or on chunky's side, but shouldn't you add 1.14 blocks? :) they display as a 3d question mark. I am using a 1.14-ready resource pack! By the way awesome plugin. Really smart. Puts together two awesome worlds: dynmap and chunky!

**Comment by leMaik** [comment]
[v2.0.1](https://github.com/leMaik/ChunkyMap/releases/tag/v2.0.1) uses the latest beta version of Chunky 2. Unfortunately, Chunky doesn't fully support all 1.14 blocks yet, but it's worth a try.

**Comment by leMaik** [comment]
I [started working](https://github.com/leMaik/chunky/tree/village-and-pillage) on support for 1.14 blocks yesterday. Barrels, looms and signs are already done, the rest will take a while.

**Comment by Leonardo-Fiori** [comment]
Oh cool! Thanks for the hard work! This plugin needs way more visibility.

May I ask another question: is it possible to run the renderer on a separate server or something? My host has an i7 4th gen but it will just die with chunkymap lol I tried also on my lan of that has a core i9 and it took a while night to render only the central part of the map

**Comment by leMaik** [comment]
Originally, this plugin was meant as a demo for a distributed render service that allowed to do just that. That service is down, but I was thinking about bringing it back to life again. :thinking:

**Comment by leMaik** [comment]
@Leonardo-Fiori It's been a while, but the fork now supports 1.14, 1.15 and even 20w12a, so I'm updating ChunkyMap right now. :hourglass_flowing_sand: The next release, v2.1.0, will support all new blocks.
